import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'inverse-primary': '#FFF3CC',
        'surface-container': '#ebeef4',
        'inverse-surface': '#2d3135',
        'secondary': '#515d84',
        'on-surface-variant': '#414754',
        'outline-variant': '#c1c6d6',
        'on-tertiary-container': '#ffffff',
        'on-tertiary': '#ffffff',
        'primary-fixed-dim': '#FFF3CC',
        'surface-container-high': '#e5e8ee',
        'error': '#ba1a1a',
        'surface': '#f7f9ff',
        'on-primary-container': '#ffffff',
        'tertiary': '#006d2c',
        'tertiary-container': '#008939',
        'surface-bright': '#f7f9ff',
        'on-secondary-fixed-variant': '#39456b',
        'on-secondary-fixed': '#0b1a3d',
        'error-container': '#ffdad6',
        'surface-variant': '#dfe3e8',
        'on-primary': '#ffffff',
        'on-background': '#181c20',
        'on-primary-fixed-variant': '#7A5800',
        'on-error-container': '#93000a',
        'surface-container-lowest': '#ffffff',
        'secondary-container': '#c4d0fd',
        'background': '#f7f9ff',
        'on-error': '#ffffff',
        'outline': '#727785',
        'surface-container-low': '#f1f4fa',
        'on-secondary': '#ffffff',
        'surface-dim': '#d7dae0',
        'on-tertiary-fixed': '#002108',
        'on-primary-fixed': '#3D2800',
        'primary': '#CC8800',
        'on-tertiary-fixed-variant': '#005320',
        'on-surface': '#181c20',
        'secondary-fixed-dim': '#b9c5f2',
        'secondary-fixed': '#dbe1ff',
        'inverse-on-surface': '#eef1f7',
        'surface-tint': '#CC8800',
        'surface-container-highest': '#dfe3e8',
        'tertiary-fixed-dim': '#6ddd81',
        'primary-fixed': '#FFF8E0',
        'primary-container': '#E8A020',
        'tertiary-fixed': '#89fa9b',
        'on-secondary-container': '#4c587f',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        'full': '9999px',
      },
      spacing: {
        'gutter': '24px',
        'lg': '48px',
        'xl': '80px',
        'xs': '4px',
        'container-max': '1280px',
        'sm': '12px',
        'md': '24px',
        'base': '8px',
      },
      fontFamily: {
        'code-snippet': ['JetBrains Mono', 'monospace'],
        'body-sm': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Plus Jakarta Sans', 'sans-serif'],
        'display-xl': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'sans': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'code-snippet': ['14px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'display-xl': ['64px', { lineHeight: '1.05', letterSpacing: '-0.03em', fontWeight: '800' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-lg': ['40px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      maxWidth: {
        'container-max': '1280px',
      },
      boxShadow: {
        'level-1': '0px 4px 24px rgba(204, 136, 0, 0.07)',
        'level-2': '0px 12px 48px rgba(204, 136, 0, 0.11)',
      },
    },
  },
  plugins: [],
}

export default config
